/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransportadoraRouteImport } from './routes/transportadora'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecicladoraRouteImport } from './routes/recicladora'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as OperadorRouteImport } from './routes/operador'
import { Route as GeradorRouteImport } from './routes/gerador'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RastreioTokenRouteImport } from './routes/rastreio.$token'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppAdminRouteImport } from './routes/_authenticated/app.admin'
import { Route as AuthenticatedAppTransportadoraIndexRouteImport } from './routes/_authenticated/app/transportadora/index'
import { Route as AuthenticatedAppRecicladoraIndexRouteImport } from './routes/_authenticated/app/recicladora/index'
import { Route as AuthenticatedAppOperadorIndexRouteImport } from './routes/_authenticated/app/operador/index'
import { Route as AuthenticatedAppGeradorIndexRouteImport } from './routes/_authenticated/app/gerador/index'
import { Route as AuthenticatedAppAdminPendingOrganizationsRouteImport } from './routes/_authenticated/app/admin/pending-organizations'
import { Route as AuthenticatedAppGeradorBateriaNovaRouteImport } from './routes/_authenticated/app/gerador/bateria.nova'
import { Route as AuthenticatedAppGeradorBateriaBatteryIdRouteImport } from './routes/_authenticated/app/gerador/bateria.$batteryId'

const TransportadoraRoute = TransportadoraRouteImport.update({
  id: '/transportadora',
  path: '/transportadora',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecicladoraRoute = RecicladoraRouteImport.update({
  id: '/recicladora',
  path: '/recicladora',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadorRoute = OperadorRouteImport.update({
  id: '/operador',
  path: '/operador',
  getParentRoute: () => rootRouteImport,
} as any)
const GeradorRoute = GeradorRouteImport.update({
  id: '/gerador',
  path: '/gerador',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RastreioTokenRoute = RastreioTokenRouteImport.update({
  id: '/rastreio/$token',
  path: '/rastreio/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppAdminRoute = AuthenticatedAppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTransportadoraIndexRoute =
  AuthenticatedAppTransportadoraIndexRouteImport.update({
    id: '/transportadora/',
    path: '/transportadora/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppRecicladoraIndexRoute =
  AuthenticatedAppRecicladoraIndexRouteImport.update({
    id: '/recicladora/',
    path: '/recicladora/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppOperadorIndexRoute =
  AuthenticatedAppOperadorIndexRouteImport.update({
    id: '/operador/',
    path: '/operador/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppGeradorIndexRoute =
  AuthenticatedAppGeradorIndexRouteImport.update({
    id: '/gerador/',
    path: '/gerador/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAdminPendingOrganizationsRoute =
  AuthenticatedAppAdminPendingOrganizationsRouteImport.update({
    id: '/pending-organizations',
    path: '/pending-organizations',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppGeradorBateriaNovaRoute =
  AuthenticatedAppGeradorBateriaNovaRouteImport.update({
    id: '/gerador/bateria/nova',
    path: '/gerador/bateria/nova',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppGeradorBateriaBatteryIdRoute =
  AuthenticatedAppGeradorBateriaBatteryIdRouteImport.update({
    id: '/gerador/bateria/$batteryId',
    path: '/gerador/bateria/$batteryId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/gerador': typeof GeradorRoute
  '/operador': typeof OperadorRoute
  '/portal': typeof PortalRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recicladora': typeof RecicladoraRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/transportadora': typeof TransportadoraRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/rastreio/$token': typeof RastreioTokenRoute
  '/app/admin': typeof AuthenticatedAppAdminRouteWithChildren
  '/app/admin/pending-organizations': typeof AuthenticatedAppAdminPendingOrganizationsRoute
  '/app/gerador/': typeof AuthenticatedAppGeradorIndexRoute
  '/app/operador/': typeof AuthenticatedAppOperadorIndexRoute
  '/app/recicladora/': typeof AuthenticatedAppRecicladoraIndexRoute
  '/app/transportadora/': typeof AuthenticatedAppTransportadoraIndexRoute
  '/app/gerador/bateria/$batteryId': typeof AuthenticatedAppGeradorBateriaBatteryIdRoute
  '/app/gerador/bateria/nova': typeof AuthenticatedAppGeradorBateriaNovaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/gerador': typeof GeradorRoute
  '/operador': typeof OperadorRoute
  '/portal': typeof PortalRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recicladora': typeof RecicladoraRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/transportadora': typeof TransportadoraRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/rastreio/$token': typeof RastreioTokenRoute
  '/app/admin': typeof AuthenticatedAppAdminRouteWithChildren
  '/app/admin/pending-organizations': typeof AuthenticatedAppAdminPendingOrganizationsRoute
  '/app/gerador': typeof AuthenticatedAppGeradorIndexRoute
  '/app/operador': typeof AuthenticatedAppOperadorIndexRoute
  '/app/recicladora': typeof AuthenticatedAppRecicladoraIndexRoute
  '/app/transportadora': typeof AuthenticatedAppTransportadoraIndexRoute
  '/app/gerador/bateria/$batteryId': typeof AuthenticatedAppGeradorBateriaBatteryIdRoute
  '/app/gerador/bateria/nova': typeof AuthenticatedAppGeradorBateriaNovaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/gerador': typeof GeradorRoute
  '/operador': typeof OperadorRoute
  '/portal': typeof PortalRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recicladora': typeof RecicladoraRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/transportadora': typeof TransportadoraRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/rastreio/$token': typeof RastreioTokenRoute
  '/_authenticated/app/admin': typeof AuthenticatedAppAdminRouteWithChildren
  '/_authenticated/app/admin/pending-organizations': typeof AuthenticatedAppAdminPendingOrganizationsRoute
  '/_authenticated/app/gerador/': typeof AuthenticatedAppGeradorIndexRoute
  '/_authenticated/app/operador/': typeof AuthenticatedAppOperadorIndexRoute
  '/_authenticated/app/recicladora/': typeof AuthenticatedAppRecicladoraIndexRoute
  '/_authenticated/app/transportadora/': typeof AuthenticatedAppTransportadoraIndexRoute
  '/_authenticated/app/gerador/bateria/$batteryId': typeof AuthenticatedAppGeradorBateriaBatteryIdRoute
  '/_authenticated/app/gerador/bateria/nova': typeof AuthenticatedAppGeradorBateriaNovaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contato'
    | '/gerador'
    | '/operador'
    | '/portal'
    | '/privacidade'
    | '/recicladora'
    | '/reset-password'
    | '/sitemap.xml'
    | '/termos'
    | '/transportadora'
    | '/app'
    | '/rastreio/$token'
    | '/app/admin'
    | '/app/admin/pending-organizations'
    | '/app/gerador/'
    | '/app/operador/'
    | '/app/recicladora/'
    | '/app/transportadora/'
    | '/app/gerador/bateria/$batteryId'
    | '/app/gerador/bateria/nova'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contato'
    | '/gerador'
    | '/operador'
    | '/portal'
    | '/privacidade'
    | '/recicladora'
    | '/reset-password'
    | '/sitemap.xml'
    | '/termos'
    | '/transportadora'
    | '/app'
    | '/rastreio/$token'
    | '/app/admin'
    | '/app/admin/pending-organizations'
    | '/app/gerador'
    | '/app/operador'
    | '/app/recicladora'
    | '/app/transportadora'
    | '/app/gerador/bateria/$batteryId'
    | '/app/gerador/bateria/nova'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contato'
    | '/gerador'
    | '/operador'
    | '/portal'
    | '/privacidade'
    | '/recicladora'
    | '/reset-password'
    | '/sitemap.xml'
    | '/termos'
    | '/transportadora'
    | '/_authenticated/app'
    | '/rastreio/$token'
    | '/_authenticated/app/admin'
    | '/_authenticated/app/admin/pending-organizations'
    | '/_authenticated/app/gerador/'
    | '/_authenticated/app/operador/'
    | '/_authenticated/app/recicladora/'
    | '/_authenticated/app/transportadora/'
    | '/_authenticated/app/gerador/bateria/$batteryId'
    | '/_authenticated/app/gerador/bateria/nova'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContatoRoute: typeof ContatoRoute
  GeradorRoute: typeof GeradorRoute
  OperadorRoute: typeof OperadorRoute
  PortalRoute: typeof PortalRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RecicladoraRoute: typeof RecicladoraRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermosRoute: typeof TermosRoute
  TransportadoraRoute: typeof TransportadoraRoute
  RastreioTokenRoute: typeof RastreioTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transportadora': {
      id: '/transportadora'
      path: '/transportadora'
      fullPath: '/transportadora'
      preLoaderRoute: typeof TransportadoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recicladora': {
      id: '/recicladora'
      path: '/recicladora'
      fullPath: '/recicladora'
      preLoaderRoute: typeof RecicladoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operador': {
      id: '/operador'
      path: '/operador'
      fullPath: '/operador'
      preLoaderRoute: typeof OperadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerador': {
      id: '/gerador'
      path: '/gerador'
      fullPath: '/gerador'
      preLoaderRoute: typeof GeradorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rastreio/$token': {
      id: '/rastreio/$token'
      path: '/rastreio/$token'
      fullPath: '/rastreio/$token'
      preLoaderRoute: typeof RastreioTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/admin': {
      id: '/_authenticated/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AuthenticatedAppAdminRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/transportadora/': {
      id: '/_authenticated/app/transportadora/'
      path: '/transportadora'
      fullPath: '/app/transportadora/'
      preLoaderRoute: typeof AuthenticatedAppTransportadoraIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/recicladora/': {
      id: '/_authenticated/app/recicladora/'
      path: '/recicladora'
      fullPath: '/app/recicladora/'
      preLoaderRoute: typeof AuthenticatedAppRecicladoraIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/operador/': {
      id: '/_authenticated/app/operador/'
      path: '/operador'
      fullPath: '/app/operador/'
      preLoaderRoute: typeof AuthenticatedAppOperadorIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/gerador/': {
      id: '/_authenticated/app/gerador/'
      path: '/gerador'
      fullPath: '/app/gerador/'
      preLoaderRoute: typeof AuthenticatedAppGeradorIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin/pending-organizations': {
      id: '/_authenticated/app/admin/pending-organizations'
      path: '/pending-organizations'
      fullPath: '/app/admin/pending-organizations'
      preLoaderRoute: typeof AuthenticatedAppAdminPendingOrganizationsRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/gerador/bateria/nova': {
      id: '/_authenticated/app/gerador/bateria/nova'
      path: '/gerador/bateria/nova'
      fullPath: '/app/gerador/bateria/nova'
      preLoaderRoute: typeof AuthenticatedAppGeradorBateriaNovaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/gerador/bateria/$batteryId': {
      id: '/_authenticated/app/gerador/bateria/$batteryId'
      path: '/gerador/bateria/$batteryId'
      fullPath: '/app/gerador/bateria/$batteryId'
      preLoaderRoute: typeof AuthenticatedAppGeradorBateriaBatteryIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppAdminRouteChildren {
  AuthenticatedAppAdminPendingOrganizationsRoute: typeof AuthenticatedAppAdminPendingOrganizationsRoute
}

const AuthenticatedAppAdminRouteChildren: AuthenticatedAppAdminRouteChildren = {
  AuthenticatedAppAdminPendingOrganizationsRoute:
    AuthenticatedAppAdminPendingOrganizationsRoute,
}

const AuthenticatedAppAdminRouteWithChildren =
  AuthenticatedAppAdminRoute._addFileChildren(
    AuthenticatedAppAdminRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAdminRoute: typeof AuthenticatedAppAdminRouteWithChildren
  AuthenticatedAppGeradorIndexRoute: typeof AuthenticatedAppGeradorIndexRoute
  AuthenticatedAppOperadorIndexRoute: typeof AuthenticatedAppOperadorIndexRoute
  AuthenticatedAppRecicladoraIndexRoute: typeof AuthenticatedAppRecicladoraIndexRoute
  AuthenticatedAppTransportadoraIndexRoute: typeof AuthenticatedAppTransportadoraIndexRoute
  AuthenticatedAppGeradorBateriaBatteryIdRoute: typeof AuthenticatedAppGeradorBateriaBatteryIdRoute
  AuthenticatedAppGeradorBateriaNovaRoute: typeof AuthenticatedAppGeradorBateriaNovaRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAdminRoute: AuthenticatedAppAdminRouteWithChildren,
  AuthenticatedAppGeradorIndexRoute: AuthenticatedAppGeradorIndexRoute,
  AuthenticatedAppOperadorIndexRoute: AuthenticatedAppOperadorIndexRoute,
  AuthenticatedAppRecicladoraIndexRoute: AuthenticatedAppRecicladoraIndexRoute,
  AuthenticatedAppTransportadoraIndexRoute:
    AuthenticatedAppTransportadoraIndexRoute,
  AuthenticatedAppGeradorBateriaBatteryIdRoute:
    AuthenticatedAppGeradorBateriaBatteryIdRoute,
  AuthenticatedAppGeradorBateriaNovaRoute:
    AuthenticatedAppGeradorBateriaNovaRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContatoRoute: ContatoRoute,
  GeradorRoute: GeradorRoute,
  OperadorRoute: OperadorRoute,
  PortalRoute: PortalRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RecicladoraRoute: RecicladoraRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermosRoute: TermosRoute,
  TransportadoraRoute: TransportadoraRoute,
  RastreioTokenRoute: RastreioTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
